### ISSUE TITLE
Web Site

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Universe#45]
Hi. After a long rest, decided to come back and with new forces to begin in testing server and website. The list of what I found once logged on to the website.
1. If the user is in the site group, writes that he has one group. http://prntscr.com/aynkw6
2. Not all translations displayed in the file so for example in the Partner profile cannot be changed as it is spelled out directly in the file user_profile.cs not in EnglishTranslation.cs and others. http://prntscr.com/aynsgc  Example: After http://prntscr.com/aynqxb to http://prntscr.com/aynr4s . Began to correct after a couple of days will be update https://github.com/ReaL-Life-3D/VU-Web-Site-Redesing
3. It is also not displayed in separate files such as 
Resident, Guest, etc I think should be written in a separate file so that everyone can translate to your language
4. Not loaded a map of the world http://prntscr.com/ayow86

How to make a user offline if the inscription was displayed in red, if online then green? http://prntscr.com/aynw57

**Comment by emperorstarfinder** [comment]
This is not actually a bug.  This just simply means the user is not a
member of any groups in-world.  If in fact however he or she is a member
of groups in-world and its not showing in the webui then in fact that
would be of concern.

**Comment by emperorstarfinder** [comment]
After reviewing your proposed changes in the repository you created it
appears your proposing a lot of changes which might actually be causing
the bugs your seeing.

I will add however your your proposed RussianTranslator.cs as we don't
apparently have a translator yet for that language if you have the flag
icon for it please commit it so I can add that as well.

The Offline and Online status the webUI already detects and will post that
on the user's profile page in the webui.  However, it thinks the user is
offline if they are inactive for a certain amount of time which is
something myself or Irishwolf will need to look at.

**Comment by emperorstarfinder** [comment]
3. It is also not displayed in separate files such as
Resident, Guest, etc I think should be written in a separate file so that everyone can translate to your language

The reason why these are not a seperate file is to ensure the site and grid stay up.  Guest just simply means the user is not logged into the grid or the webui.  Consider it a login check so that needs to be where it is.

**Comment by IrishwolfStarfinder** [comment]
Good evening,

I reviewed the issues indicated here.  After testing I am unable to
reproduce the following:

1. If the user is in the site group, writes that he has one group.

Are you setting yourself as a system user? or regular user?  System users
have intentionally been limited in what they can do group role wise for
extra security.

2. Not all translations displayed in the file so for example in the
Partner profile cannot be changed as it is spelled out directly in the
file user_profile.cs not in EnglishTranslation.cs and others.

Yes, this is correct there are some issues we are aware of relating to the
translators in how they translate on the website.  We do have plans to try
to update the way translations work for the webui to correct this issue.

3. It is also not displayed in separate files such as
Resident, Guest, etc I think should be written in a separate file so that
everyone can translate to your language

As EmperorStarfinder has indicated here, The reason you see Resident, and
Guest in the same file is done on purpose.  This purpose is to ensure the
webui properly detects whether the user is actually logged in or not in
the same way this is done in the grid architecture as well.  It probably
is not the cleanest way to do a login check on the webui but right now it
is the way its done for various services to work correctly such as user
accounts, currency, etc.  Hopefully we will figure out a better way to
handle this soon without it also hurting viewers :)

4. Not loaded a map of the world

In testing world map this appears to be working with the current version
of Virtual Universe.  Perhaps in your modifications you might have by
accident broke the world map?  I recommend trying a clean fresh copy of
Virtual Universe to see if this persists without modifications.  If it
does not then you will know its in a modification you might have done.  If
it still happens then this would be a bug we will need to address.

5.  How to make a user offline if the inscription was displayed in red, if
online then green?

In the user's web profile this is essentially already being done but the
plan is to enhance this further with a few more things in the web
profiles.  I will add this one to my list of web profile enhancements.

Irishwolf Starfinder
Core Developer
Web and Network Design
Group Member
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
4. Not loaded a map of the world

Just confirmed this bug.  This is not in his local code this is an issue in Virtual Universe itself.

**Comment by LifeGold** [comment]
With a map figured out I forgot to change it in code using jQuery-1 jQuery-2.2.3.min

**Comment by emperorstarfinder** [comment]
So I am going to assume then that theres still old referencing to the old jQuery 1 still lingering somewhere

**Comment by LifeGold** [comment]
The question how to add a new page to the site? For example I need a page for Terms in the html but that would be at the job site did not influence it in any way.

**Comment by IrishwolfStarfinder** [comment]
That actually is a good idea to have on the webui.  There are a couple of
steps to do here to add this.

1. You will need to add the menu stuff in
Universe.Modules.Web.Migrators.PageMigrator.cs

2. You will need to create the necessary .cs file to add to
Universe.Modules.Web.HTML

3. You will then need to create the .html file and put this in bin/html
and restart your servers.

If it is something that can wait a day or two I will add it into the
webui.  We do have some great improvements for the webui coming out in a
few days as well.

Irishwolf Starfinder
Core Developer
Web and Network Design
Group Member
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
It actually is a good idea and probably one we should have done from the start.  Adding enhancement and assigning for further development.

**Comment by LifeGold** [comment]
Added all the only issue arose next. For example the terms of my service is not in the General menu of the website, and at the bottom as in the screenshot http://prntscr.com/azyt0k. How do I output it so that when you click on the link at the bottom of the website has opened a page Terms of Service this has not gone menu.

**Comment by IrishwolfStarfinder** [comment]
I guess I will need to look and see what you have done in the code itself
to see whats going on.  If you commit it to the repository you linked in
your initial report on this issue, I will take a look after I eat dinner,
as I don't want my wife upset that I don't each such a great meal.

Irishwolf Starfinder
Core Developer
Web and Network Design
Group Member
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment]
Well. Thanks waiting for an answer. Bon appetit.

**Comment by LifeGold** [comment]
And another question I can not understand what the problem is, I want the menu to move to another tab, deleted the file PagesMigrator.the drop-down menu in the CS. But it still remained. What to do? http://prntscr.com/azznq5

**Comment by IrishwolfStarfinder** [comment]
Sorry for the delay, dinner was excellent as always :)

Unfortunately your running into problems that are caused by code becoming
so far outdated that they near their EOL (End Of Life) in the support
cycle for maintaining that version of code.  The builtin webui dates back
to the beginnings of Aurora-Sim apparently and so has many problems
associated with it.

Another piece of this right now is the webui currently uses line coding in
its menus and not block coding.  In fact Linden Labs did that originally
with Secondlife (but used php).  They have since moved to what we call
block coding for their websites which allows for a crisper more efficient
and professional design and is considered to be part of the development
standards of the day by website developers.

You may also experience bugs caused unintentionally as members of the
development team are hard at work behind the scenes fixing all kinds of
problems detected by Coverity scans.

You shouldn't remove the PageMigrator.cs as it is expected by other parts
of the webui.  So by removing that you stand to cause unintended bugs. 
The best idea would be to keep the pages the way we have them for now and
modify them as needed that way for your grid.  In the development process
for Virtual Universe Version 1.0.3 we will be introducing a brand new
modern, state of the art, and modular webui that will have the ability to
do much more and look even better.

If you are able to wait a day or so I will be able to get the webui
working as intended while cleanup continues in preparation for Virtual
Universe Version 1.0.2 Release.

I have downloaded whats in the repository you indicated initially in this
issue report and will go through it to see if theres anything we will be
able to use as well.

Irishwolf Starfinder
Core Developer
Web and Network Design
Group Member
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by IrishwolfStarfinder** [comment]
Good morning,

I fixed the world map issue before I went to take a nap last night and
pushed commit: 88914e4b93bb96b06872c4ab67cb66b2afa6d718 dated May 4, 2016
to master this morning.  This appears to have been updated to the correct
jQuery file just accidental typos in the file name.  World map in the
webui now works as normal.  This fixes sub issue number 4 in the initial
report.

Also... to correct my last comment last night

In regards my reference to Secondlife's website....

I was referring to the php/html part of their site and not the underlying
c# coding.  This comment is moot however as initial review of your
repository indicates you have updated the html side using bootstrap.

There are underlying issues in the C# side of the codebase which are being
worked through by the development team, which may or may not at times
create unintended or unforeseen bugs in the code.  As they become found
they are being corrected.

Also please be sure you keep up with the configuration file updates.

The AssetServiceHandler has been moved from Services.ini to
Grid/ServerConfiguration/Data/Data.ini (I made this mistake yesterday not
realizing it had been moved and inadvertantly put it back myself, so even
a developer can get things wrong now and then).

I will be working on the webui today as we work to get ready to start
introducing new features in Version 1.0.3

There are no new features expected from Version 1.0.2 RC2 through Version
1.0.2 Release, except for code cleanup and bug fixes.

Irishwolf Starfinder
Core Developer
Web and Network Design
Group Member
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
User reports page manager is not working.  Additionally the world map and region profile info appears to still not be working properly as well.

Emperor Starfinder
Founder/ Core Developer
CEO
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment]
Compiled on the new server, the menu did not appear policy center

**Comment by LifeGold** [comment]
Fixed

**Comment by IrishwolfStarfinder** [comment]
I haven't implemented the policy center stuff yet but I will be in the
next few hours

**Comment by LifeGold** [comment]
Search user gives this error. http://prntscr.com/b0kpt9

**Comment by IrishwolfStarfinder** [comment]
Good Morning,

Are you modifying against the most current version of the Master
repository?  If so that means theres probably a search parameter off that
i will need to correct.

Irishwolf Starfinder
Core Developer
Web and Network Design
Group Member
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment]
Not changed nothing, it was so long ago I simply forgot to write a vow a few months.

**Comment by emperorstarfinder** [comment]
Good afternoon guys,

It looks like the search issue your referring to is a bug found by BriakallistaStarfinder and has since been fixed to allow for better handling of search results.  

I am currently in the process of testing and debugging an upcoming commit that will effectively delete the current files in the repository and update them with fresh files with cleaned up code.  This is known as a re-base.  This commit will also introduce a number of fixes and corrections including fixes to issues found by Coverity scans.  We are in the process of going through the entire code base and there is approximately 258,600 lines of code to go through and fix problems founded by the coverity scans.  We hope to have all these fixes implemented before we push Virtual Universe Version 1.0.2 Release out the door.

Beginning with the development phase of Virtual Universe Version 1.0.3 we will be using the development repository at https://github.com/Virtual-Universe/Virtual-Dev

Bug reports can still be submitted to the Virtual-Universe repository and is the repository you will want to use for a production level grid (an example of a production level grid is Secondlife).  Feature Requests should be posted on the issue tracker for both repositories to ensure a good discussion.

I expect to be pushing the commit sometime this evening.

Emperor Starfinder
Founder/ Core Developer
CEO
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
Issue appears to be resolved.  Core developer assigned has indicated new updates to the webui (builtin and standalone) will be introduced during development of Virtual Universe Version 1.0.3 Development phase.  So closing as there is Feature Request #33 which involves upgrades and updates to the webui.  Additionally user can fork Virtual-Universe repository and commit changes to their fork of the Virtual-Universe repository and submit a pull request as described in Issue #48 

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
